/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as AdminRouteRouteImport } from "./routes/admin/route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AdminIndexRouteImport } from "./routes/admin/index"
import { Route as AdminUsersRouteImport } from "./routes/admin/users"
import { Route as AdminSigninRouteImport } from "./routes/admin/signin"
import { Route as AdminProfileRouteImport } from "./routes/admin/profile"
import { Route as AdminImportRouteImport } from "./routes/admin/import"
import { Route as AdminHoursRouteImport } from "./routes/admin/hours"
import { Route as AdminEventsRouteImport } from "./routes/admin/events"
import { Route as AdminCreditIndexRouteImport } from "./routes/admin/credit/index"
import { Route as AdminCreditCustomerIdRouteImport } from "./routes/admin/credit/$customerId"

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSigninRoute = AdminSigninRouteImport.update({
  id: "/signin",
  path: "/signin",
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: "/import",
  path: "/import",
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHoursRoute = AdminHoursRouteImport.update({
  id: "/hours",
  path: "/hours",
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: "/events",
  path: "/events",
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCreditIndexRoute = AdminCreditIndexRouteImport.update({
  id: "/credit/",
  path: "/credit/",
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCreditCustomerIdRoute = AdminCreditCustomerIdRouteImport.update({
  id: "/credit/$customerId",
  path: "/credit/$customerId",
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/admin": typeof AdminRouteRouteWithChildren
  "/admin/events": typeof AdminEventsRoute
  "/admin/hours": typeof AdminHoursRoute
  "/admin/import": typeof AdminImportRoute
  "/admin/profile": typeof AdminProfileRoute
  "/admin/signin": typeof AdminSigninRoute
  "/admin/users": typeof AdminUsersRoute
  "/admin/": typeof AdminIndexRoute
  "/admin/credit/$customerId": typeof AdminCreditCustomerIdRoute
  "/admin/credit/": typeof AdminCreditIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/admin/events": typeof AdminEventsRoute
  "/admin/hours": typeof AdminHoursRoute
  "/admin/import": typeof AdminImportRoute
  "/admin/profile": typeof AdminProfileRoute
  "/admin/signin": typeof AdminSigninRoute
  "/admin/users": typeof AdminUsersRoute
  "/admin": typeof AdminIndexRoute
  "/admin/credit/$customerId": typeof AdminCreditCustomerIdRoute
  "/admin/credit": typeof AdminCreditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/admin": typeof AdminRouteRouteWithChildren
  "/admin/events": typeof AdminEventsRoute
  "/admin/hours": typeof AdminHoursRoute
  "/admin/import": typeof AdminImportRoute
  "/admin/profile": typeof AdminProfileRoute
  "/admin/signin": typeof AdminSigninRoute
  "/admin/users": typeof AdminUsersRoute
  "/admin/": typeof AdminIndexRoute
  "/admin/credit/$customerId": typeof AdminCreditCustomerIdRoute
  "/admin/credit/": typeof AdminCreditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/admin"
    | "/admin/events"
    | "/admin/hours"
    | "/admin/import"
    | "/admin/profile"
    | "/admin/signin"
    | "/admin/users"
    | "/admin/"
    | "/admin/credit/$customerId"
    | "/admin/credit/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/admin/events"
    | "/admin/hours"
    | "/admin/import"
    | "/admin/profile"
    | "/admin/signin"
    | "/admin/users"
    | "/admin"
    | "/admin/credit/$customerId"
    | "/admin/credit"
  id:
    | "__root__"
    | "/"
    | "/admin"
    | "/admin/events"
    | "/admin/hours"
    | "/admin/import"
    | "/admin/profile"
    | "/admin/signin"
    | "/admin/users"
    | "/admin/"
    | "/admin/credit/$customerId"
    | "/admin/credit/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/admin": {
      id: "/admin"
      path: "/admin"
      fullPath: "/admin"
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/": {
      id: "/admin/"
      path: "/"
      fullPath: "/admin/"
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/admin/users": {
      id: "/admin/users"
      path: "/users"
      fullPath: "/admin/users"
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/admin/signin": {
      id: "/admin/signin"
      path: "/signin"
      fullPath: "/admin/signin"
      preLoaderRoute: typeof AdminSigninRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/admin/profile": {
      id: "/admin/profile"
      path: "/profile"
      fullPath: "/admin/profile"
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/admin/import": {
      id: "/admin/import"
      path: "/import"
      fullPath: "/admin/import"
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/admin/hours": {
      id: "/admin/hours"
      path: "/hours"
      fullPath: "/admin/hours"
      preLoaderRoute: typeof AdminHoursRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/admin/events": {
      id: "/admin/events"
      path: "/events"
      fullPath: "/admin/events"
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/admin/credit/": {
      id: "/admin/credit/"
      path: "/credit"
      fullPath: "/admin/credit/"
      preLoaderRoute: typeof AdminCreditIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/admin/credit/$customerId": {
      id: "/admin/credit/$customerId"
      path: "/credit/$customerId"
      fullPath: "/admin/credit/$customerId"
      preLoaderRoute: typeof AdminCreditCustomerIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminEventsRoute: typeof AdminEventsRoute
  AdminHoursRoute: typeof AdminHoursRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSigninRoute: typeof AdminSigninRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCreditCustomerIdRoute: typeof AdminCreditCustomerIdRoute
  AdminCreditIndexRoute: typeof AdminCreditIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminEventsRoute: AdminEventsRoute,
  AdminHoursRoute: AdminHoursRoute,
  AdminImportRoute: AdminImportRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSigninRoute: AdminSigninRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCreditCustomerIdRoute: AdminCreditCustomerIdRoute,
  AdminCreditIndexRoute: AdminCreditIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
